repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--preview", "--line-length", "79"]
  - repo: https://github.com/Tesla2000/temp-reorder-python-imports
    rev: v0.0.1
    hooks:
      - id: reorder-python-imports
        args: [
          --py37-plus,
          --py39-plus,
          --retain-pre-import,
          'True',
          --application-directories,
          "DND_character_creator",
        ]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [ --remove-all-unused-imports, --in-place ]
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        args: [ "--ignore=E203,W503,E501" ]
#  - repo: https://github.com/Tesla2000/Autodoc-hook
#    rev: '0.1.2'
#    hooks:
#      - id: autodoc
#        stages: [push]
#        args: [--llm, gpt-4o-mini, --api_keys=OPENAI_API_KEY]
default_stages: [commit]